version: 2

sources:
  - name: customer
    database: snowflake_sample_data
    schema: tpcds_sf10tcl
    tables:
      - name: customer
      - name: customer_address
      - name: customer_demographics

  - name: order
    database: snowflake_sample_data
    schema: tpch_sf1
    tables:
      - name: orders